Sovol config Updates
MarlinFirmware/Configurations pull request #804
Opened 2022-08-21 16:49 UTC by ils15

Update Configuration for Sovol Printers

Insert easy coment line to enable/disable 3D touch

2022-08-21 23:55 UTC, Farva42 requested changes
The original Board addition is not needed as this is covered by the CrealityV22 & CrealityV221 configs. It also looks like you are using an older config file ie 2.0.9.2 vs the current 2.1.x which will cause issues on the existing configs but a current 2.1.x for the new examples.

2022-08-22 00:00 UTC, ils15 commented
My mistake
I thinked v22 is a silent board
I will update v22 and v221 boards to match with new settings
Thanks

2022-08-22 00:07 UTC, Farva42 commented
V22 is the stock board with A4988 drivers. V221 is the silent board with TMC2208_STANDALONE.

2022-08-22 09:12 UTC, ils15 commented
> V22 is the stock board with A4988 drivers. V221 is the silent board with TMC2208_STANDALONE.

Great
Now i'm updated things here
thanks

2022-08-24 20:49 UTC, ils15 reviewed
Update with Z Probe Offset and Babystepping Combined

2022-08-24 21:25 UTC, ils15 reviewed
Parametrize SV01 BTT SKR Mini E3 V3

2022-08-26 03:12 UTC, thinkyhead commented on config/examples/Sovol/SV-01/CrealityV22/Configuration_adv.h
> +  #define LCD_LANGUAGE_3 es
This seems a bit too personalized.

2022-08-26 03:52 UTC, thinkyhead commented
I put in the necessary time to clean up and update this stunning submission.
Please review the commits for changes and verify that nothing got lost in the cleanup.

2022-08-26 09:58 UTC, ils15 reviewed
Everything seems to be fine
Thanks @thinkyhead

2022-09-02 01:19 UTC, thinkyhead commented
Okay, then. I went ahead and corrected the various extant errors, regressions, and outdated options, bringing this into better parity with the development tree bugfix-2.1.x. This ought to be reviewed by some other SOVOL users before it is merged, since it contains many personally tailored preferences that may not be embraced by other users.

2022-09-30 22:47 UTC, merged